{{- $depName := printf "%s" (include "deploymentName" (dict "root" .Values "defaultname" "constellation-messaging" )) }}
{{- $srvTargetPort := .Values.service.targetPort }}{{ if .Values.pegaMessagingTargetPort }}{{ $srvTargetPort = .Values.pegaMessagingTargetPort }}{{ end }}
{{- if .Values.enabled }}
kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ $depName }}
  labels:
    app: {{ $depName }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ $depName }}
  template:
    metadata:
      labels:
        app: {{ $depName }}
    spec:
      imagePullSecrets:
      - name: {{ include "backingservicesRegistrySecret" ( dict "root" .Values "defaultname" "constellation" ) }}
      {{ if .Values.docker.imagePullSecretNames }}
      {{- range .Values.docker.imagePullSecretNames }}
      - name: {{ . }}
      {{- end }}
      {{ else if .Values.imagePullSecretNames }}
      {{- range .Values.imagePullSecretNames }}
      - name: {{ . }}
      {{- end }}
      {{ end }}
      containers:
      - name: {{ $depName }}
        imagePullPolicy: {{ .Values.docker.messaging.imagePullPolicy }}
        image: {{ .Values.docker.messaging.image }}
        args:
        - --max-semi-space-size=1024
        - port={{ $srvTargetPort }}
        - path={{ .Values.urlPath }}
        livenessProbe:
          initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
          timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
          periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
          successThreshold: {{ .Values.livenessProbe.successThreshold }}
          failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
          httpGet:
            path: {{ .Values.urlPath }}/ping
            port: {{ $srvTargetPort }}
        readinessProbe:
          initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
          timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
          periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
          successThreshold: {{ .Values.readinessProbe.successThreshold }}
          failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
          httpGet:
            path: {{ .Values.urlPath }}/ping
            port: {{ $srvTargetPort }}
        ports:
        - containerPort: {{ $srvTargetPort }}
{{ end }}