{{- if .Values.enabled }}
kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.name }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      imagePullSecrets:
      {{- range .Values.imagePullSecretNames }}
        - name: {{ . }}
      {{- end }}
      containers:
      - name: c11n-messaging
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        image: {{ .Values.image }}
        resources:
          {{ if .Values.resources }}
          {{ toYaml .Values.resources | nindent 10 }}
          {{- end }}
        securityContext:
          {{- if .Values.securityContext }}
          {{ toYaml .Values.securityContext | nindent 10 }}
          {{- end }}
        args:
          - --max-semi-space-size=1024
          - port={{ .Values.pegaMessagingTargetPort }}
          - path=/c11n-messaging
        ports:
        - containerPort: {{ .Values.pegaMessagingTargetPort }}
{{ end }}
