{{- $depName := printf "%s" (include "deploymentName" (dict "root" .Values "defaultname" "constellation" )) }}
{{- if .Values.enabled }}
kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ $depName }}
  labels:
    app: {{ $depName }}
    {{- if and (.Values.deployment) (.Values.deployment.labels) }}
    {{ toYaml .Values.deployment.labels | nindent 4 }}
    {{- end }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ $depName }}
  template:
    metadata:
      labels:
        app: {{ $depName }}
        {{- if .Values.podLabels }}
        {{ toYaml .Values.podLabels | nindent 8 }}
        {{- end }}
      {{- if .Values.podAnnotations }}
      annotations:
        {{ toYaml .Values.podAnnotations | nindent 8 }}
      {{- end }}
    spec:
      {{- if .Values.serviceAccountName }}
      serviceAccountName: {{ .Values.serviceAccountName }}
      {{- end }}
      {{- if .Values.customerAssetVolumeClaimName }}
      volumes:
        - name: {{ $depName }}-appstatic-assets
          persistentVolumeClaim:
            claimName: {{ .Values.customerAssetVolumeClaimName }}
      {{- end }}
      imagePullSecrets:
      - name: {{ include "backingservicesRegistrySecret" ( dict "root" .Values "defaultname" "constellation" ) }}
      {{ if .Values.docker.imagePullSecretNames }}
      {{- range .Values.docker.imagePullSecretNames }}
      - name: {{ . }}
      {{- end }}
      {{ else if .Values.imagePullSecretNames }}
      {{- range .Values.imagePullSecretNames }}
      - name: {{ . }}
      {{- end }}
      {{ end }}
      containers:
      - name: constellation
        imagePullPolicy: {{ .Values.docker.constellation.imagePullPolicy }}
        image: {{ .Values.docker.constellation.image }}
        resources:
          {{ if .Values.resources }}
          {{ toYaml .Values.resources | nindent 10 }}
          {{- end }}
        securityContext:
          {{- if .Values.securityContext }}
          {{ toYaml .Values.securityContext | nindent 10 }}
          {{- end }}
        {{ if .Values.customerAssetVolumeClaimName }}
        volumeMounts:
         - name: {{ $depName }}-appstatic-assets
           mountPath: /usr/src/app/dist/customers
        {{- end }}
        args:
        - port={{ .Values.service.targetPort }}
        # constellation URL path, if you change it, you need to change ingress template files too
        - urlPath={{ .Values.urlPath }}
        - logLevel={{ .Values.logLevel }}
        livenessProbe:
          initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
          timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
          periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
          successThreshold: {{ .Values.livenessProbe.successThreshold }}
          failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
          httpGet:
            path: {{ .Values.urlPath }}/buildInfo.json
            port: {{ .Values.service.targetPort }}
        readinessProbe:
          initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
          timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
          periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
          successThreshold: {{ .Values.readinessProbe.successThreshold }}
          failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
          httpGet:
            path: {{ .Values.urlPath }}/buildInfo.json
            port: {{ .Values.service.targetPort }}
        ports:
        - containerPort: {{ .Values.service.targetPort }}
{{- include "podAffinity" .Values | indent 6 }}
{{- include "tolerations" .Values | indent 6 }}
{{ end }}