{{ if (eq (include "performDeployment" .) "true") }}

{{ if (eq (include "isExternalSearch" .) "true") }}
# The deployment generates this file to deploy Elasticsearch internally when the external search URL is blank (or the default value is left) 
# AND no search service is enabled.
{{ else }}
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: {{ template "searchName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "searchName" . }}
    component: Pega
spec:
  selector:
    matchLabels:
      app: {{ template "searchName" . }}
      component: "Search"
  serviceName: {{ template "searchName" . }}
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      labels:
        app: {{ template "searchName" . }}
        component: "Search"
{{- if .Values.podAnnotations }}
      annotations:
{{ toYaml .Values.podAnnotations | indent 8 }}
{{- end }}
    spec:
      {{ if ne .Values.global.provider "openshift" }}
      securityContext:
        fsGroup: {{ .Values.podSecurityContext.runAsUser | default 1000 }}
      {{ end }}
      initContainers:
        # Init containers
      {{- if and (eq .Values.global.provider "openshift") (eq .Values.set_data_owner_on_startup true) }}
      - name: set-dir-owner
        image: {{ .Values.global.utilityImages.busybox.image }}
        imagePullPolicy: {{ .Values.global.utilityImages.busybox.imagePullPolicy }}
        command: ['sh', '-c', 'chown -R {{ .Values.podSecurityContext.runAsUser | default 1000 }}:{{ .Values.podSecurityContext.runAsUser | default 1000 }} /usr/share/elasticsearch/data']
        volumeMounts:
        - name: esstorage
          mountPath: /usr/share/elasticsearch/data
      {{ end }}
      {{- if .Values.set_vm_max_map_count }}
      - name: set-max-map-count
        image: {{ .Values.global.utilityImages.busybox.image }}
        imagePullPolicy: {{ .Values.global.utilityImages.busybox.imagePullPolicy }}
        command: ['sysctl', '-w', 'vm.max_map_count=262144']
        securityContext:
          privileged: true
      {{ end }}
      containers:
      - name: search
        image: {{ .Values.image }}
{{- if ( .Values.imagePullPolicy ) }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
{{- end }}
{{- if ne .Values.global.provider "openshift" }}
        securityContext:
          runAsUser: {{ .Values.podSecurityContext.runAsUser | default 1000 }}
{{- end }}
        env:
        - name: HOST_LIST
          value: {{ template "searchName" . }}-transport
        - name: ES_JAVA_OPTS
          value: "-Xmx2g -Xms2g"
        - name: UNICAST_HOSTS
          value: {{ template "searchName" . }}-transport
        - name: NUMBER_OF_MASTERS
        {{- if .Values.env }}
          value: "{{ .Values.env.MINIMUM_MASTER_NODES }}"
        {{- else }}
          value: {{ .Values.minimumMasterNodes | quote }}
        {{- end }}
{{- if .Values.custom }}
{{- if .Values.custom.env }}
{{ toYaml .Values.custom.env | indent 8 }}
{{- end }}
{{- end }}
        resources:
          requests:
            cpu: "{{ .Values.cpuRequest }}"
            memory: "{{ .Values.memRequest }}"
          limits:
            cpu: "{{ .Values.cpuLimit }}"
            memory: "{{ .Values.memLimit }}"
        ports:
        - containerPort: 9200
          name: http
        - containerPort: 9300
          name: transport
        livenessProbe:
          tcpSocket:
            port: transport
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /_cat
            port: http
          initialDelaySeconds: 20
          timeoutSeconds: 5
        volumeMounts:
        - name: esstorage
          mountPath: /usr/share/elasticsearch/data
      imagePullSecrets:
      - name: {{ template "pegaRegistrySecret" $}}
  volumeClaimTemplates:
  - metadata:
      name: esstorage
    spec:
      accessModes: [ ReadWriteOnce ]
      resources:
        requests:
          storage: {{ .Values.volumeSize }}
{{- if ( .Values.global.storageClassName ) }}
      storageClassName: {{ .Values.global.storageClassName }}
{{ end }}
{{ end }}
{{ end }}
