---
# Configure Traefik for load balancing:
#   If enabled: true, Traefik is deployed automatically.
#   If enabled: false, Traefik is not deployed and load balancing must be configured manually.
#   Pega recommends enabling Traefik on providers other than Openshift and eks.
#   On Openshift, Traefik is ignored and Pega uses Openshift's built-in load balancer.
#   On eks it is recommended to use aws alb ingress controller.
traefik:
  enabled: true
  # Set any additional Traefik parameters. These values will be used by Traefik's helm chart.
  # See https://github.com/helm/charts/blob/master/stable/traefik/values.yaml
  # Set traefik.serviceType to "LoadBalancer" on gke, aks, and pks
  serviceType: NodePort
  # If enabled is set to "true", ssl will be enabled for traefik
  ssl:
    enabled: false
  rbac:
    enabled: true
  service:
    nodePorts:
      # NodePorts for traefik service.
      http: 30080
      https: 30443
  resources:
    requests:
      # Enter the CPU Request for traefik
      cpu: 200m
      # Enter the memory request for traefik
      memory: 200Mi
    limits:
      # Enter the CPU Limit for traefik
      cpu: 500m
      # Enter the memory limit for traefik
      memory: 500Mi
# Set this to true to install aws-alb-ingress-controller. Follow below guidelines specific to each provider,
# For EKS - set this to true.
# GKE or AKS or K8s or Openshift - set this to false and enable traefik.
aws-alb-ingress-controller:
  enabled: false
  ## Resources created by the ALB Ingress controller will be prefixed with this string
  clusterName: "YOUR_EKS_CLUSTER_NAME"
  ## Auto Discover awsRegion from ec2metadata, set this to true and omit awsRegion when ec2metadata is available.
  autoDiscoverAwsRegion: true
  ## AWS region of k8s cluster, required if ec2metadata is unavailable from controller pod
  ## Required if autoDiscoverAwsRegion != true
  awsRegion: "YOUR_EKS_CLUSTER_REGION"
  ## Auto Discover awsVpcID from ec2metadata, set this to true and omit awsVpcID: " when ec2metadata is available.
  autoDiscoverAwsVpcID: true
  ## VPC ID of k8s cluster, required if ec2metadata is unavailable from controller pod
  ## Required if autoDiscoverAwsVpcID != true
  awsVpcID: "YOUR_EKS_CLUSTER_VPC_ID"
  extraEnv:
    AWS_ACCESS_KEY_ID: "YOUR_AWS_ACCESS_KEY_ID"
    AWS_SECRET_ACCESS_KEY: "YOUR_AWS_SECRET_ACCESS_KEY"
# Configure EFK stack for logging:
#   For a complete EFK stack: elasticsearch, fluentd-elasticsearch, and kibana should all be enabled
#   Pega recommends deploying EFK only on k8s
#   On Openshift, see https://docs.openshift.com/container-platform/3.11/install_config/aggregate_logging.html
#   On EKS, see https://eksworkshop.com/logging/

# Replace false with true to deploy EFK.
# Do not remove &deploy_efk; it is a yaml anchor which is referenced by the EFK subcharts.
deploy_efk: &deploy_efk false

elasticsearch:
  enabled: *deploy_efk
  # Set any additional elastic search parameters. These values will be used by elasticsearch helm chart.
  # See https://github.com/helm/charts/tree/master/stable/elasticsearch/values.yaml
  #
  # If you need to change this value then you will also need to replace the same
  # part of the value within the following properties further below:
  #
  #   kibana.files.kibana.yml.elasticsearch.url
  #   fluentd-elasticsearch.elasticsearch.host
  #
  fullnameOverride: "elastic-search"

kibana:
  enabled: *deploy_efk
  # Set any additional kibana parameters. These values will be used by Kibana's helm chart.
  # See https://github.com/helm/charts/tree/master/stable/kibana/values.yaml
  files:
    kibana.yml:
      elasticsearch.url: http://elastic-search-client:9200
  service:
    externalPort: 80
  ingress:
    # If enabled is set to "true", an ingress is created to access kibana.
    enabled: true
    # Enter the domain name to access kibana via a load balancer.
    hosts:
      - "YOUR_WEB.KIBANA.EXAMPLE.COM"

fluentd-elasticsearch:
  enabled: *deploy_efk
  # Set any additional fluentd-elasticsearch parameters. These values will be used by fluentd-elasticsearch's helm chart.
  # See https://github.com/helm/charts/tree/master/stable/fluentd-elasticsearch/values.yaml
  elasticsearch:
    host: elastic-search-client
    buffer_chunk_limit: 250M
    buffer_queue_limit: 30

metrics-server:
  # Set this to true to install metrics-server. Follow below guidelines specific to each provider,
  # open-source Kubernetes, Openshift & EKS - mandatory to set this to true if any tier as hpa.enabled is true
  # GKE or AKS - set this to false since metrics-server is installed in the cluster by default.
  enabled: false
  # Set any additional metrics-server parameters. These values will be used by metrics-server's helm chart.
  # See https://github.com/helm/charts/blob/master/stable/metrics-server/values.yaml
  args:
    - --logtostderr
# The order in which to consider different Kubelet node address types when connecting to Kubelet.
# Uncomment below arguemnt if host names are not resolvable from metrics server pod.
# This setting is not required for public cloud providers & openshift enterprise. It may be required for open-source Kubernetes.
# - --kubelet-preferred-address-types=InternalIP,Hostname,InternalDNS,ExternalDNS,ExternalIP
# Uncomment below arguemnt to skip verifying Kubelet CA certificates.
# Not recommended for production usage, but can be useful in test clusters with self-signed Kubelet serving certificates.
# This setting is not required for public cloud providers & openshift enterprise. It may be required for open-source Kubernetes.
# - --kubelet-insecure-tls
