apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helm-basic-example.fullname" . }}
  labels:
    # These labels are required by helm. You can read more about required labels in the chart best pracices guide:
    # https://docs.helm.sh/chart_best_practices/#standard-labels
    helm.sh/chart: {{ include "helm-basic-example.chart" . }}
    app.kubernetes.io/name: {{ include "helm-basic-example.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "helm-basic-example.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "helm-basic-example.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: app
          {{- $repo := required "containerImageRepo is required" .Values.containerImageRepo }}
          {{- $tag := required "containerImageTag is required" .Values.containerImageTag }}
          image: "{{ $repo }}:{{ $tag }}"
          ports:
          - containerPort: 80
