# Enter the number of search nodes for Kubernetes to deploy (minimum 1).
replicas: 1
# If externalURL is set, no search nodes will be deployed automatically, and Pega will use this search node url.
externalURL: "http://pega-search"
# Enter the docker image used to deploy Elasticsearch. This value will be ignored if using an external url.
# Push the Elasticsearch image to your internal docker registry. This must be the same registry as the docker section above.
image: "YOUR_ELASTICSEARCH_IMAGE:TAG"
# Enter the CPU limit for each search node (recommended 1).
cpuLimit: 1
# Enter the Memory limit for each search node (recommended 4Gi).
memLimit: "4Gi"
# Enter the volume size limit for each search node (recommended 5Gi).
volumeSize: "5Gi"
env:
  # IMPORTANT: https://www.elastic.co/guide/en/elasticsearch/reference/current/important-settings.html#minimum_master_nodes
  # To prevent data loss, it is vital to configure the discovery.zen.minimum_master_nodes setting so that each master-eligible
  # node knows the minimum number of master-eligible nodes that must be visible in order to form a cluster.
  # This value should be configured using formula (n/2) + 1 where n is replica count or desired capacity
  MINIMUM_MASTER_NODES: "1"
